#!/bin/bash
# ==============================================================================
# Start the example service
# s6-overlay docs: https://github.com/just-containers/s6-overlay
# ==============================================================================

# Declare variables
declare subdomain

# Get the 'subdomain' key from the user config options.
# subdomain=$(bashio::config 'subdomain')

# Check if 'subdomain' is empty
echo "Subdomain is empty. Generating from MAC address."

# Specify the network interface (adjust as necessary)
INTERFACE="eth0"

# Retrieve the MAC address for the interface
MAC_ADDRESS=$(cat /sys/class/net/${INTERFACE}/address)

# Call the binary to get the hash result. Adjust the path if your binary is not in the PATH
HASHED_MAC=$(./hash_binary "${MAC_ADDRESS}")

# Use the dynamically generated subdomain (last 4 characters of the hash)
subdomain=${HASHED_MAC}
echo "Using generated subdomain: $subdomain"

python3 -u /usr/client/client.py "${subdomain}" token
